on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: |
          sudo npm install -g yarn
          yarn install          
          yarn tc
          yarn build
          cd examples/slicing
          yarn install
          yarn build
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: examples/slicing/dist